Systems Benchmark
XRFoundation/XREngine-development-test-suite pull request #82
Opened 2024-03-26 02:47 UTC by MichaelEstes

2024-03-26 19:35 UTC, HexaField requested changes

2024-03-26 19:35 UTC, HexaField commented on engine/Register.ts
> +    if (!sceneState.sceneLoaded.value) return
we should avoid reliance on sceneLoaded if possible. we can simplify this into useQuery calls to decouple from needing a scene to be loaded at all

2024-05-02 21:45 UTC, HexaField commented on engine/benchmarks/AvatarBenchmark.ts
> +  const avatarState = getMutableState(AvatarState)
we must only mutate event sourced state via actions

2024-05-14 04:34 UTC, HexaField requested changes

2024-05-14 04:34 UTC, HexaField commented on engine/TestUtils.ts
> +  const avatars = useHookstate([] as string[])
can we just use a `useFind` with a map here?

2024-06-12 22:39 UTC, HexaField requested changes

2024-06-12 22:39 UTC, HexaField commented on sceneRoute.tsx
> +  const projectName = 'ee-development-test-suite'
let's make these parameters for useRouteScene

2024-06-14 01:17 UTC, HexaField requested changes

2024-06-14 01:17 UTC, HexaField commented on examples/avatarMocap.tsx
> +const poses = [
now that the mocap test files have moved to this projec we need to update the import glob

2024-06-14 03:03 UTC, HexaField requested changes
a small regression here is we've lost the ability to persist which example we have open in the URL, meaning reloading the page requires us to find and open that example again. we should just append the id or name into the search params of the URL.

We should also not load the avatar into any of these pages unless it explicitly is showing something about the user's active avatar, though I think that needs some changes in the engine.

2024-06-14 03:03 UTC, HexaField commented on engine/examples/ExamplesComponent.tsx
> +    Reactor: (props: { parent: Entity; onLoad: (entity: Entity) => void }) => {
i don't think the UVOLs provided here are supposed to be public domain, whether or not we can use them I think we should try and find ones we do definitely own, and probably just disable the UVOL example for now.

2024-06-14 03:03 UTC, HexaField commented on engine/examples/ExamplesComponent.tsx
> +export const ExamplesComponent = defineComponent({
Since we don't need this serialized to a scene any more, i think it's more appropriate for this to be a state instead. It would be nice to combine the XRUI and regular UI, we could have the component examples under a sub-section grouped together or something.

2024-06-17 22:24 UTC, MichaelEstes commented
> a small regression here is we've lost the ability to persist which example we have open in the URL, meaning reloading the page requires us to find and open that example again. we should just append the id or name into the search params of the URL.
> 
> We should also not load the avatar into any of these pages unless it explicitly is showing something about the user's active avatar, though I think that needs some changes in the engine.

2024-06-17 22:34 UTC, MichaelEstes commented on engine/examples/ExamplesComponent.tsx
> +    Reactor: (props: { parent: Entity; onLoad: (entity: Entity) => void }) => {
"We should also not load the avatar into any of these pages unless it explicitly is showing something about the user's active avatar, though I think that needs some changes in the engine." 

Do you want this to be a part of this ticket?

2024-06-18 03:14 UTC, HexaField commented on engine/examples/ExamplesComponent.tsx
> +    Reactor: (props: { parent: Entity; onLoad: (entity: Entity) => void }) => {
nah we can throw that in the backlog

2024-06-18 04:25 UTC, HexaField approved these changes

2024-06-18 17:31 UTC, merged